#!/bin/bash
# script for running http server using nodejs (http://nodejs.org/)
SCRIPTPATH="$(pwd)/${BASH_SOURCE[0]}"
SCRIPTDIR="$(dirname $SCRIPTPATH)"
cd "$SCRIPTDIR/../"
echo "-------------------------------------------------------------------"
echo "Started serving the project directory. Ctrl-C to stop."
echo "-------------------------------------------------------------------"
node $SCRIPTDIR/http.js $*