#!/bin/bash

SCRIPTPATH="$(pwd)/${BASH_SOURCE[0]}"
SCRIPTDIR="$(dirname $SCRIPTPATH)"
cd "$SCRIPTDIR/../"
echo "-------------------------------------------------------------------"
echo "Started tdd tests using karma."
echo "-------------------------------------------------------------------"
karma start $SCRIPTDIR/../tests/unit-karma.conf.js $*
